CREATE TABLE "CUSTOMERS"
(
  "ID" SERIAL PRIMARY KEY,
  "FIRST_NAME" VARCHAR(255) NOT NULL,
  "LAST_NAME" VARCHAR(255) NOT NULL,
  "EMAIL" VARCHAR(50) UNIQUE NOT NULL,
  "CREATED_AT" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE "ACCOUNTS"
(
  "ID" SERIAL PRIMARY KEY,
  "CUSTOMER_ID" INT NOT NULL REFERENCES "CUSTOMERS"("ID") ON DELETE CASCADE,
  "ACCOUNT_TYPE" VARCHAR(50) NOT NULL,
  "BALANCE" NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK ("BALANCE" >= 0),
  "CURRENCY" VARCHAR(3) NOT NULL DEFAULT 'USD',
  "CREATED_AT" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE "TRANSACTIONS" 
(
 "ID" BIGSERIAL PRIMARY KEY,
 "ACCOUNT_ID" INT NOT NULL REFERENCES "ACCOUNTS"("ID") ON DELETE CASCADE,
 "TXN_TYPE" VARCHAR(50) NOT NULL,
 "AMOUNT" NUMERIC(18,2) NOT NULL CHECK ("AMOUNT" > 0),
 "RELATED_ACCOUNT_ID" INT NULL,
 "STATUS" VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
 "CREATED_AT" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
